import type { Metadata } from "next";
import { Inter, Signika, Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const openRunde = localFont({
  variable: "--font-open-runde",
  src: [
    {
      path: "../public/font/web/OpenRunde-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/web/OpenRunde-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/font/web/OpenRunde-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/font/web/OpenRunde-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

const chirp = localFont({
  variable: "--font-twitter",
  src: [
    {
      path: "../public/font/chirp/Chirp_Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/chirp/Chirp_Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/font/chirp/Chirp_Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/font/chirp/Chirp_Heavy.woff",
      weight: "800",
      style: "normal",
    },
  ],
  display: "swap",
});

const signika = Signika({
  subsets: ["latin"],
  variable: "--font-signika",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${inter.className} ${inter.variable} ${signika.variable} ${openRunde.variable} ${chirp.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
