import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const openRunde = localFont({
  variable: "--font-open-runde",
  src: [
    { path: "../public/font/web/OpenRunde-Regular.woff2", weight: "400", style: "normal" },
    { path: "../public/font/web/OpenRunde-Medium.woff2", weight: "500", style: "normal" },
    { path: "../public/font/web/OpenRunde-Semibold.woff2", weight: "600", style: "normal" },
    { path: "../public/font/web/OpenRunde-Bold.woff2", weight: "700", style: "normal" },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${inter.variable} ${openRunde.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
